<?php
/* SVN FILE: $Id$ */
/**
 * Short description for file.
 *
 * In this file, you can set up 'templates' for every tag generated by the tag
 * generator.
 *
 * PHP versions 4 and 5
 *
 * CakePHP :  Rapid Development Framework <http://www.cakephp.org/>
 * Copyright (c)	2006, Cake Software Foundation, Inc.
 *								1785 E. Sahara Avenue, Suite 490-204
 *								Las Vegas, Nevada 89104
 *
 * Licensed under The MIT License
 * Redistributions of files must retain the above copyright notice.
 *
 * @filesource
 * @copyright		Copyright (c) 2006, Cake Software Foundation, Inc.
 * @link				http://www.cakefoundation.org/projects/info/cakephp CakePHP Project
 * @package			cake
 * @subpackage		cake.cake.app.config
 * @since			CakePHP v 0.2.9
 * @version			$Revision$
 * @modifiedby		$LastChangedBy$
 * @lastmodified	$Date$
 * @license			http://www.opensource.org/licenses/mit-license.php The MIT License
 */

// Tag template for a link tag.
$tags['metalink'] = '<link href="%s" title="%s"%s />';

// Tag template for a link.
$tags['link'] = '<a href="%s" %s>%s</a>';

// Tag template for a mailto: link.
$tags['mailto'] = '<a href="mailto:%s" %s>%s</a>';

// Tag template for opening form tag.
$tags['form'] = '<form %s>';

// Tag template for an input type='text' tag.
$tags['input'] = '<input name="data[%s][%s]" %s/>';

// Tag template for an input type='textarea' tag
$tags['textarea'] = '<textarea name="data[%s][%s]" %s>%s</textarea>';

// Tag template for an input type='hidden' tag.
$tags['hidden'] = '<input type="hidden" name="data[%s][%s]" %s/>';

// Tag template for a textarea tag.
$tags['textarea'] = '<textarea name="data[%s][%s]" %s>%s</textarea>';

// Tag template for a input type='checkbox ' tag.
$tags['checkbox'] = '<input type="checkbox" name="data[%s][%s]" %s/>';

// Tag template for a input type='radio' tag.
$tags['radio'] = '<input type="radio" name="data[%s][%s]" id="%s" %s />%s';

// Tag template for a select opening tag.
$tags['selectstart'] = '<select name="data[%s][%s]" %s>';

// Tag template for a select opening tag.
$tags['selectmultiplestart'] = '<select name="data[%s][%s][]" %s>';

// Tag template for an empty select option tag.
$tags['selectempty'] = '<option value="" %s>&nbsp;</option>';

// Tag template for a select option tag.
$tags['selectoption'] = '<option value="%s" %s>%s</option>';

// Tag template for a closing select tag.
$tags['selectend'] = '</select>';

// Tag template for a option group tag.
$tags['optiongroup'] = '<optgroup label="%s"%s>';
$tags['optiongroupend'] = '</optgroup>';

// Tag template for a password tag.
$tags ['password'] = '<input type="password" name="data[%s][%s]" %s/>';

// Tag template for a file input tag.
$tags ['file'] = '<input type="file" name="data[%s][%s]" %s/>';

// Tag template for a file input tag with no associated model.
$tags ['file_no_model'] = '<input type="file" name="%s" %s/>';

// Tag template for a submit button tag.
$tags ['submit'] = '<input type="submit" %s/>';

// Tag template for a image input tag.
$tags['submitimage'] = '<input type="image" src="%s" %s/>';

// Tag template for an image tag.
$tags ['image'] = '<img src="%s" %s/>';

// Tag template for a table header tag.
$tags ['tableheader'] = '<th%s>%s</th>';

// Tag template for table headers row tag.
$tags ['tableheaderrow'] = '<tr%s>%s</tr>';

// Tag template for a table cell tag.
$tags ['tablecell'] = '<td%s>%s</td>';

// Tag template for a table row tag.
$tags ['tablerow'] = '<tr%s>%s</tr>';

// Tag templates for a block-level element (DIV).
$tags ['block'] = '<div%s>%s</div>';
$tags ['blockstart'] = '<div%s>';
$tags ['blockend'] = '</div>';

// Tag templates for a paragraph element.
$tags['para'] = '<p%s>%s</p>';
$tags['parastart'] = '<p%s>';

// Tag templates for a label element.
$tags['label'] = '<label for="%s"%s>%s</label>';

// Tag templates for fieldset and legend element.
$tags['fieldset'] = '<fieldset><legend>%s</legend>%s</fieldset>';
$tags['fieldsetstart'] = '<fieldset><legend>%s</legend>';
$tags['fieldsetend'] = '</fieldset>';
$tags['legend'] = '<legend>%s</legend>';

// Tag template for a CSS link tag.
$tags ['css'] = '<link rel="%s" type="text/css" href="%s" %s/>';

// Tag template for a CSS tag block.
$tags ['style'] = '<style type="text/css"%s>%s</style>';

// Tag template for a charset meta-tag.
$tags ['charset'] = '<meta http-equiv="Content-Type" content="text/html; charset=%s" />';

// Tag template for inline JavaScript.
$tags ['javascriptblock'] = '<script type="text/javascript">%s</script>';
$tags['javascriptstart'] = '<script type="text/javascript">';

// Tag template for included JavaScript.
$tags ['javascriptlink'] = '<script type="text/javascript" src="%s"></script>';