<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @since         5.4.0
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
namespace Cake\Attribute\Resolver;

use Brick\VarExporter\VarExporter;
use Cake\Attribute\Resolver\ValueObject\AttributeInfo;
use Cake\Log\Log;
use Cake\Utility\Filesystem;
use Throwable;

/**
 * Artifact storage for compiled attribute data.
 *
 * Stores AttributeInfo arrays as compiled PHP files that can be loaded
 * quickly on subsequent requests. Uses brick/varexporter for serialization
 * to properly handle readonly objects and enums.
 */
class Artifact
{
    /**
     * @var array<\Cake\Attribute\Resolver\ValueObject\AttributeInfo>|null
     */
    private ?array $memoryCache = null;

    /**
     * Constructor.
     *
     * @param string $path Path to the artifact file
     * @param bool $validateFiles Whether to validate source file modification times
     */
    public function __construct(
        protected string $path,
        protected bool $validateFiles = false,
    ) {
    }

    /**
     * Store attribute information to the artifact file.
     *
     * @param iterable<\Cake\Attribute\Resolver\ValueObject\AttributeInfo> $attributeInfos Attribute information to store
     * @return void
     */
    public function set(iterable $attributeInfos): void
    {
        if (!is_array($attributeInfos)) {
            $attributeInfos = iterator_to_array($attributeInfos, false);
        }

        $this->memoryCache = $attributeInfos;

        try {
            $timestamp = date('Y-m-d H:i:s');
            $count = count($attributeInfos);
            $exported = VarExporter::export($attributeInfos, VarExporter::ADD_RETURN);

            $content = <<<PHP
<?php
// phpcs:ignoreFile
/**
 * CakePHP Attribute Resolver Artifact
 *
 * This file contains pre-compiled attribute metadata for fast loading.
 * Generated: {$timestamp}
 * Attributes: {$count}
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is automatically generated and will be overwritten.
 */

declare(strict_types=1);

{$exported}

PHP;

            $filesystem = new Filesystem();
            $filesystem->dumpFile($this->path, $content);
        } catch (Throwable $e) {
            Log::warning(sprintf(
                'Failed to write artifact file: %s - %s',
                $this->path,
                $e->getMessage(),
            ));
        }
    }

    /**
     * Retrieve attribute information from the artifact file.
     *
     * @return array<\Cake\Attribute\Resolver\ValueObject\AttributeInfo>|null
     */
    public function get(): ?array
    {
        if (!file_exists($this->path)) {
            // Return memory cache even if file doesn't exist (cache survives file deletion)
            return $this->memoryCache;
        }

        // When validation is enabled, check if artifact is stale before using cache
        if ($this->validateFiles && !$this->isValid()) {
            $this->memoryCache = null;

            return null;
        }

        // Return from memory cache if available
        if ($this->memoryCache !== null) {
            return $this->memoryCache;
        }

        try {
            $data = $this->load();

            if (!is_array($data)) {
                Log::warning(sprintf(
                    'Invalid artifact data in file: %s',
                    $this->path,
                ));

                return null;
            }

            foreach ($data as $item) {
                if (!$item instanceof AttributeInfo) {
                    Log::warning(sprintf(
                        'Invalid artifact item type in file: %s',
                        $this->path,
                    ));

                    return null;
                }
            }

            $this->memoryCache = $data;

            return $data;
        } catch (Throwable $e) {
            Log::warning(sprintf(
                'Failed to load artifact file: %s - %s',
                $this->path,
                $e->getMessage(),
            ));

            return null;
        }
    }

    /**
     * Delete the artifact file.
     *
     * @return bool True if the file was deleted, false if it didn't exist
     */
    public function delete(): bool
    {
        $this->memoryCache = null;

        if (!file_exists($this->path)) {
            return false;
        }

        return unlink($this->path);
    }

    /**
     * Load raw data from the artifact file.
     *
     * @return mixed
     */
    private function load(): mixed
    {
        return require $this->path;
    }

    /**
     * Validate that the artifact is still fresh by checking source file modification times.
     *
     * Compares each source file's current modification time against the stored fileTime
     * from when the artifact was created. If any source file is newer, the artifact is stale.
     *
     * @return bool True if valid, false if any source file has changed since artifact creation
     */
    public function isValid(): bool
    {
        if (!file_exists($this->path)) {
            return false;
        }

        try {
            $data = $this->load();

            if (!is_array($data)) {
                return false;
            }

            foreach ($data as $item) {
                if (!$item instanceof AttributeInfo) {
                    return false;
                }

                if ($item->filePath && file_exists($item->filePath)) {
                    clearstatcache(true, $item->filePath);
                    $currentTime = filemtime($item->filePath);
                    // Compare current file time with stored time from when artifact was created
                    if ($currentTime !== false && $currentTime > $item->fileTime) {
                        return false;
                    }
                }
            }

            return true;
        } catch (Throwable) {
            return false;
        }
    }
}
