#!/bin/bash
################################################################################
#
# Bake is a shell script for running CakePHP bake script
# PHP versions 4 and 5
#
# CakePHP(tm) :  Rapid Development Framework (http://www.cakephp.org)
# Copyright 2005-2007, Cake Software Foundation, Inc.
#
# Licensed under The MIT License
# Redistributions of files must retain the above copyright notice.
#
# @filesource
# @copyright		Copyright 2005-2007, Cake Software Foundation, Inc.
# @link				http://www.cakefoundation.org/projects/info/cakephp CakePHP(tm) Project
# @package			cake
# @subpackage		cake.cake.console
# @since				CakePHP(tm) v 1.2.0.5012
# @version			$Revision$
# @modifiedby		$LastChangedBy$
# @lastmodified	$Date$
# @license			http://www.opensource.org/licenses/mit-license.php The MIT License
#
################################################################################
clear

LIB=${0/%cake/}
APP=`pwd`

exec php -q ${LIB}cake.php -working "${APP}" "$@"

exit;