#!/usr/bin/env bash
################################################################################
#
# Bake is a shell script for running CakePHP bake script
# PHP 5
#
# CakePHP(tm) :  Rapid Development Framework (http://cakephp.org)
# Copyright 2005-2012, Cake Software Foundation, Inc.
#
# Licensed under The MIT License
# Redistributions of files must retain the above copyright notice.
#
# @copyright    Copyright 2005-2012, Cake Software Foundation, Inc.
# @link         http://cakephp.org CakePHP(tm) Project
# @package      app.Console
# @since        CakePHP(tm) v 2.0
# @license      MIT License (http://www.opensource.org/licenses/mit-license.php)
#
################################################################################
if [[ `uname` =~ 'Darwin' ]]; then
	ME=$0
else
	ME=$(readlink -f $0)
fi
LIB=$(cd -P -- "$(dirname -- "$ME")" && pwd -P) && LIB=$LIB/$(basename -- "$ME")

while [ -h "$LIB" ]; do
	DIR=$(dirname -- "$LIB")
	SYM=$(readlink "$LIB")
	LIB=$(cd "$DIR" && cd $(dirname -- "$SYM") && pwd)/$(basename -- "$SYM")
done

LIB=$(dirname -- "$LIB")/
APP=$(dirname $(cd $(dirname $ME) && pwd))

exec php -q "$LIB"cake.php -working "$APP" "$@"

exit;
