name: Bug Report
description: Create a bug report
labels: ["defect"]
body:
  - type: textarea
    attributes:
      label: Description
      description: "Please provide a description and way to reproduce the problem."
      placeholder: |
        Please use the CakePHP Slack channel, Discord channel or IRC channel for questions.

        https://cakephp.org/get-involved#getHelp
    validations:
      required: true
  - type: input
    attributes:
      label: CakePHP Version
      description: "The CakePHP version used."
      placeholder: "4.4.0"
    validations:
      required: true
  - type: input
    attributes:
      label: PHP Version
      description: "The php version used, if needed."
      placeholder: "8.0"
    validations:
      required: false
