name: Bug Report
description: Create a bug report
labels: ["defect"]
body:
  - type: textarea
    attributes:
      label: Description
      description: "Please provide a description and way to reproduce the problem."
      placeholder: |
        This issue tracker is *not* a support forum.
        Please use the CakePHP Slack channel, Discord channel or Discourse forum for support questions.
        https://book.cakephp.org/5/en/intro/where-to-get-help.html
    validations:
      required: true
  - type: input
    attributes:
      label: CakePHP Version
      description: "The CakePHP version used."
      placeholder: "5.0"
    validations:
      required: true
  - type: input
    attributes:
      label: PHP Version
      description: "The php version used, if needed."
      placeholder: "8.0"
    validations:
      required: false
