<?PHP
//////////////////////////////////////////////////////////////////////////
// + $Id$
// +------------------------------------------------------------------+ //
// + Cake <https://developers.nextco.com/cake/>                       + //
// + Copyright: (c) 2005, Cake Authors/Developers                     + //
// + Author(s): Michal Tatarynowicz aka Pies <tatarynowicz@gmail.com> + //
// +            Larry E. Masters aka PhpNut <nut@phpnut.com>          + //
// +            Kamil Dzielinski aka Brego <brego.dk@gmail.com>       + //
// +------------------------------------------------------------------+ //
// + Licensed under The MIT License                                   + //
// + Redistributions of files must retain the above copyright notice. + //
// + See: http://www.opensource.org/licenses/mit-license.php          + //
//////////////////////////////////////////////////////////////////////////

/**
 * In this file, you can set up 'templates' for every tag generated by the tag
 * generator.
 *
 * @filesource 
 * @author Cake Authors/Developers
 * @copyright Copyright (c) 2005, Cake Authors/Developers
 * @link https://developers.nextco.com/cake/wiki/Authors Authors/Developers
 * @package cake
 * @subpackage cake.config
 * @since Cake v 0.2.9
 * @version $Revision$
 * @modifiedby $LastChangedBy$
 * @lastmodified $Date$
 * @license http://www.opensource.org/licenses/mit-license.php The MIT License
 */

/**
 * Tag template for a link. 
 */
define('TAG_LINK', '<a href="%s"%s>%s</a>');

/**
 * Tag template for openning form tag. 
 */
define('TAG_FORM', '<form %s>');

/**
 * Tag template for an input tag. 
 */
define('TAG_INPUT',			'<input name="data[%s]" %s/>');

/**
 * Tag template for a hidden tag. 
 */
define('TAG_HIDDEN',			'<input type="hidden" name="data[%s]" %s/>');

/**
 * Tag template for a textarea tag. 
 */
define('TAG_AREA',			'<textarea name="data[%s]"%s>%s</textarea>');

/**
 * Tag template for a checkbox input tag. 
 */
define('TAG_CHECKBOX',		'<label for="tag_%s"><input type="checkbox" name="data[%s]" id="tag_%s" %s/>%s</label>');

/**
 * Tag template for a radio input tag. 
 */
define('TAG_RADIOS', 		'<label for="tag_%s"><input type="radio" name="data[%s]" id="tag_%s" %s/>%s</label>');

/**
 * Tag template for a select openning tag. 
 */
define('TAG_SELECT_START', '<select name="data[%s]"%s>');

/**
 * Tag template for an empty select option tag. 
 */
define('TAG_SELECT_EMPTY', '<option value=""%s></option>');

/**
 * Tag template for a select option tag. 
 */
define('TAG_SELECT_OPTION','<option value="%s"%s>%s</option>');

/**
 * Tag template for a closing select tag. 
 */
define('TAG_SELECT_END',	'</select>');

/**
 * Tag template for a password tag. 
 */
define('TAG_PASSWORD',		'<input type="password" name="data[%s]" %s/>');

/**
 * Tag template for a file input tag. 
 */
define('TAG_FILE',			'<input type="file" name="%s" %s/>');

/**
 * Tag template for a submit tag. 
 */
define('TAG_SUBMIT',			'<input type="submit" %s/>');

/**
 * Tag template for an image tag. 
 */
define('TAG_IMAGE',			'<img src="%s" alt="%s" %s/>');

/**
 * Tag template for a table header tag. 
 */
define('TAG_TABLE_HEADER',	'<th%s>%s</th>');

/**
 * Tag template for table headers row tag. 
 */
define('TAG_TABLE_HEADERS','<tr%s>%s</tr>');

/**
 * Tag template for a table cell tag. 
 */
define('TAG_TABLE_CELL',	'<td%s>%s</td>');

/**
 * Tag template for a table row tag. 
 */
define('TAG_TABLE_ROW',		'<tr%s>%s</tr>');

/**
 * Tag template for a CSS meta-tag. 
 */
define('TAG_CSS',          '<link rel="%s" type="text/css" href="%s" />');

/**
 * Tag template for a charset meta-tag. 
 */
define('TAG_CHARSET',      '<meta http-equiv="Content-Type" content="text/html; charset=%s" />');

?>
