name: Cancel
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - requested
permissions:
  contents: read

jobs:
  cancel:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.10.0
      with:
        workflow_id: ${{ github.event.workflow.id }}
